name: publish bicep modules to github container registry

on:
    workflow_dispatch:
    push:
        paths:
        - './bicep/infrastructure/resources/**.bicep'
jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: access GHCR
              run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: publish storage template
              run: |
                bicep publish ./bicep/infrastructure/resources/storageAccount.bicep \
                 --target br:ghcr.io/${{ github.repository }}/storageaccount:v0.0.1 --with-source 